{
    "data":{
       "nearest":{
          "edges":[
             {
                "node":{
                   "place":{
                      "lat":60.16094,
                      "lon":24.64666,
                      "name":"Kattilatanhua",
                      "gtfsId":"HSL:2421211",
                      "code":"E4203",
                      "desc":"Kattilalaaksonkatu",
                      "locationType":"STOP",
                      "vehicleType":3,
                      "stoptimesWithoutPatterns":[
                         {
                            "scheduledArrival":63060,
                            "realtimeArrival":63060,
                            "arrivalDelay":0,
                            "scheduledDeparture":63060,
                            "realtimeDeparture":63060,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Jorvi via Espoon keskus",
                            "trip":{
                               "routeShortName":"542"
                            }
                         },
                         {
                            "scheduledArrival":63180,
                            "realtimeArrival":63180,
                            "arrivalDelay":0,
                            "scheduledDeparture":63180,
                            "realtimeDeparture":63180,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Matinkylä (M)",
                            "trip":{
                               "routeShortName":"158"
                            }
                         },
                         {
                            "scheduledArrival":64860,
                            "realtimeArrival":64860,
                            "arrivalDelay":0,
                            "scheduledDeparture":64860,
                            "realtimeDeparture":64860,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Jorvi via Espoon keskus",
                            "trip":{
                               "routeShortName":"542"
                            }
                         },
                         {
                            "scheduledArrival":64980,
                            "realtimeArrival":64980,
                            "arrivalDelay":0,
                            "scheduledDeparture":64980,
                            "realtimeDeparture":64980,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Matinkylä (M)",
                            "trip":{
                               "routeShortName":"158"
                            }
                         },
                         {
                            "scheduledArrival":66660,
                            "realtimeArrival":66660,
                            "arrivalDelay":0,
                            "scheduledDeparture":66660,
                            "realtimeDeparture":66660,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Jorvi via Espoon keskus",
                            "trip":{
                               "routeShortName":"542"
                            }
                         }
                      ]
                   },
                   "distance":492
                }
             },
             {
                "node":{
                   "place":{
                      "lat":60.16095,
                      "lon":24.646428,
                      "name":"Kattilatanhua",
                      "gtfsId":"HSL:2421212",
                      "code":"E4204",
                      "desc":"Kattilalaaksonkatu",
                      "locationType":"STOP",
                      "vehicleType":3,
                      "stoptimesWithoutPatterns":[
                         {
                            "scheduledArrival":62460,
                            "realtimeArrival":62550,
                            "arrivalDelay":90,
                            "scheduledDeparture":62460,
                            "realtimeDeparture":62550,
                            "departureDelay":90,
                            "realtime":true,
                            "realtimeState":"UPDATED",
                            "headsign":"Kiviruukki",
                            "trip":{
                               "routeShortName":"158"
                            }
                         },
                         {
                            "scheduledArrival":63120,
                            "realtimeArrival":63120,
                            "arrivalDelay":0,
                            "scheduledDeparture":63120,
                            "realtimeDeparture":63120,
                            "departureDelay":0,
                            "realtime":true,
                            "realtimeState":"UPDATED",
                            "headsign":"Soukka via Espoonlahti",
                            "trip":{
                               "routeShortName":"542"
                            }
                         },
                         {
                            "scheduledArrival":64260,
                            "realtimeArrival":64260,
                            "arrivalDelay":0,
                            "scheduledDeparture":64260,
                            "realtimeDeparture":64260,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Kiviruukki",
                            "trip":{
                               "routeShortName":"158"
                            }
                         },
                         {
                            "scheduledArrival":64920,
                            "realtimeArrival":64920,
                            "arrivalDelay":0,
                            "scheduledDeparture":64920,
                            "realtimeDeparture":64920,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Soukka via Espoonlahti",
                            "trip":{
                               "routeShortName":"542"
                            }
                         },
                         {
                            "scheduledArrival":66060,
                            "realtimeArrival":66060,
                            "arrivalDelay":0,
                            "scheduledDeparture":66060,
                            "realtimeDeparture":66060,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Kiviruukki",
                            "trip":{
                               "routeShortName":"158"
                            }
                         }
                      ]
                   },
                   "distance":507
                }
             },
             {
                "node":{
                   "place":{
                      "lat":60.16351,
                      "lon":24.65042,
                      "name":"Kattilarinne",
                      "gtfsId":"HSL:2421219",
                      "code":"E4211",
                      "desc":"Kattilalaaksonkatu",
                      "locationType":"STOP",
                      "vehicleType":3,
                      "stoptimesWithoutPatterns":[
                         {
                            "scheduledArrival":63120,
                            "realtimeArrival":63120,
                            "arrivalDelay":0,
                            "scheduledDeparture":63120,
                            "realtimeDeparture":63120,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Jorvi via Espoon keskus",
                            "trip":{
                               "routeShortName":"542"
                            }
                         },
                         {
                            "scheduledArrival":63180,
                            "realtimeArrival":63180,
                            "arrivalDelay":0,
                            "scheduledDeparture":63180,
                            "realtimeDeparture":63180,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Matinkylä (M)",
                            "trip":{
                               "routeShortName":"158"
                            }
                         },
                         {
                            "scheduledArrival":64920,
                            "realtimeArrival":64920,
                            "arrivalDelay":0,
                            "scheduledDeparture":64920,
                            "realtimeDeparture":64920,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Jorvi via Espoon keskus",
                            "trip":{
                               "routeShortName":"542"
                            }
                         },
                         {
                            "scheduledArrival":64980,
                            "realtimeArrival":64980,
                            "arrivalDelay":0,
                            "scheduledDeparture":64980,
                            "realtimeDeparture":64980,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Matinkylä (M)",
                            "trip":{
                               "routeShortName":"158"
                            }
                         },
                         {
                            "scheduledArrival":66720,
                            "realtimeArrival":66720,
                            "arrivalDelay":0,
                            "scheduledDeparture":66720,
                            "realtimeDeparture":66720,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Jorvi via Espoon keskus",
                            "trip":{
                               "routeShortName":"542"
                            }
                         }
                      ]
                   },
                   "distance":509
                }
             },
             {
                "node":{
                   "place":{
                      "lat":60.16306,
                      "lon":24.64959,
                      "name":"Kattilarinne",
                      "gtfsId":"HSL:2421220",
                      "code":"E4212",
                      "desc":"Kattilalaaksonkatu",
                      "locationType":"STOP",
                      "vehicleType":3,
                      "stoptimesWithoutPatterns":[
                         {
                            "scheduledArrival":62460,
                            "realtimeArrival":62548,
                            "arrivalDelay":88,
                            "scheduledDeparture":62460,
                            "realtimeDeparture":62550,
                            "departureDelay":90,
                            "realtime":true,
                            "realtimeState":"UPDATED",
                            "headsign":"Kiviruukki",
                            "trip":{
                               "routeShortName":"158"
                            }
                         },
                         {
                            "scheduledArrival":63060,
                            "realtimeArrival":63060,
                            "arrivalDelay":0,
                            "scheduledDeparture":63060,
                            "realtimeDeparture":63060,
                            "departureDelay":0,
                            "realtime":true,
                            "realtimeState":"UPDATED",
                            "headsign":"Soukka via Espoonlahti",
                            "trip":{
                               "routeShortName":"542"
                            }
                         },
                         {
                            "scheduledArrival":64260,
                            "realtimeArrival":64260,
                            "arrivalDelay":0,
                            "scheduledDeparture":64260,
                            "realtimeDeparture":64260,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Kiviruukki",
                            "trip":{
                               "routeShortName":"158"
                            }
                         },
                         {
                            "scheduledArrival":64860,
                            "realtimeArrival":64860,
                            "arrivalDelay":0,
                            "scheduledDeparture":64860,
                            "realtimeDeparture":64860,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Soukka via Espoonlahti",
                            "trip":{
                               "routeShortName":"542"
                            }
                         },
                         {
                            "scheduledArrival":66060,
                            "realtimeArrival":66060,
                            "arrivalDelay":0,
                            "scheduledDeparture":66060,
                            "realtimeDeparture":66060,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Kiviruukki",
                            "trip":{
                               "routeShortName":"158"
                            }
                         }
                      ]
                   },
                   "distance":515
                }
             },
             {
                "node":{
                   "place":{
                      "lat":60.16229,
                      "lon":24.6596,
                      "name":"Vehas",
                      "gtfsId":"HSL:2434204",
                      "code":"E4938",
                      "desc":"Nöykkiönkatu",
                      "locationType":"STOP",
                      "vehicleType":3,
                      "stoptimesWithoutPatterns":[
                         {
                            "scheduledArrival":62400,
                            "realtimeArrival":62400,
                            "arrivalDelay":0,
                            "scheduledDeparture":62400,
                            "realtimeDeparture":62400,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Matinkylä (M)",
                            "trip":{
                               "routeShortName":"157"
                            }
                         },
                         {
                            "scheduledArrival":62820,
                            "realtimeArrival":62923,
                            "arrivalDelay":103,
                            "scheduledDeparture":62820,
                            "realtimeDeparture":62925,
                            "departureDelay":105,
                            "realtime":true,
                            "realtimeState":"UPDATED",
                            "headsign":"Espoonlahti",
                            "trip":{
                               "routeShortName":"125"
                            }
                         },
                         {
                            "scheduledArrival":63300,
                            "realtimeArrival":63300,
                            "arrivalDelay":0,
                            "scheduledDeparture":63300,
                            "realtimeDeparture":63300,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Matinkylä (M)",
                            "trip":{
                               "routeShortName":"159"
                            }
                         },
                         {
                            "scheduledArrival":64260,
                            "realtimeArrival":64260,
                            "arrivalDelay":0,
                            "scheduledDeparture":64260,
                            "realtimeDeparture":64260,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Matinkylä (M)",
                            "trip":{
                               "routeShortName":"157"
                            }
                         },
                         {
                            "scheduledArrival":64620,
                            "realtimeArrival":64620,
                            "arrivalDelay":0,
                            "scheduledDeparture":64620,
                            "realtimeDeparture":64620,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Espoonlahti",
                            "trip":{
                               "routeShortName":"125"
                            }
                         }
                      ]
                   },
                   "distance":577
                }
             },
             {
                "node":{
                   "place":{
                      "lat":60.16474,
                      "lon":24.65108,
                      "name":"Kattilavuori",
                      "gtfsId":"HSL:2421214",
                      "code":"E4206",
                      "desc":"Kattilalaaksonkatu",
                      "locationType":"STOP",
                      "vehicleType":3,
                      "stoptimesWithoutPatterns":[
                         {
                            "scheduledArrival":62400,
                            "realtimeArrival":62487,
                            "arrivalDelay":87,
                            "scheduledDeparture":62400,
                            "realtimeDeparture":62487,
                            "departureDelay":87,
                            "realtime":true,
                            "realtimeState":"UPDATED",
                            "headsign":"Kiviruukki",
                            "trip":{
                               "routeShortName":"158"
                            }
                         },
                         {
                            "scheduledArrival":63060,
                            "realtimeArrival":63060,
                            "arrivalDelay":0,
                            "scheduledDeparture":63060,
                            "realtimeDeparture":63060,
                            "departureDelay":0,
                            "realtime":true,
                            "realtimeState":"UPDATED",
                            "headsign":"Soukka via Espoonlahti",
                            "trip":{
                               "routeShortName":"542"
                            }
                         },
                         {
                            "scheduledArrival":64200,
                            "realtimeArrival":64200,
                            "arrivalDelay":0,
                            "scheduledDeparture":64200,
                            "realtimeDeparture":64200,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Kiviruukki",
                            "trip":{
                               "routeShortName":"158"
                            }
                         },
                         {
                            "scheduledArrival":64860,
                            "realtimeArrival":64860,
                            "arrivalDelay":0,
                            "scheduledDeparture":64860,
                            "realtimeDeparture":64860,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Soukka via Espoonlahti",
                            "trip":{
                               "routeShortName":"542"
                            }
                         },
                         {
                            "scheduledArrival":66000,
                            "realtimeArrival":66000,
                            "arrivalDelay":0,
                            "scheduledDeparture":66000,
                            "realtimeDeparture":66000,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Kiviruukki",
                            "trip":{
                               "routeShortName":"158"
                            }
                         }
                      ]
                   },
                   "distance":663
                }
             },
             {
                "node":{
                   "place":{
                      "lat":60.162555,
                      "lon":24.661038,
                      "name":"Vehas",
                      "gtfsId":"HSL:2434205",
                      "code":"E4939",
                      "desc":"Eestinmalmintie",
                      "locationType":"STOP",
                      "vehicleType":3,
                      "stoptimesWithoutPatterns":[
                         {
                            "scheduledArrival":61560,
                            "realtimeArrival":61584,
                            "arrivalDelay":24,
                            "scheduledDeparture":61560,
                            "realtimeDeparture":61586,
                            "departureDelay":26,
                            "realtime":true,
                            "realtimeState":"UPDATED",
                            "headsign":"Matinkylä (M)",
                            "trip":{
                               "routeShortName":"158"
                            }
                         },
                         {
                            "scheduledArrival":62160,
                            "realtimeArrival":62160,
                            "arrivalDelay":0,
                            "scheduledDeparture":62160,
                            "realtimeDeparture":62160,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Tapiola (M) via Niittykumpu (M)",
                            "trip":{
                               "routeShortName":"125"
                            }
                         },
                         {
                            "scheduledArrival":63360,
                            "realtimeArrival":63360,
                            "arrivalDelay":0,
                            "scheduledDeparture":63360,
                            "realtimeDeparture":63360,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Matinkylä (M)",
                            "trip":{
                               "routeShortName":"158"
                            }
                         },
                         {
                            "scheduledArrival":64020,
                            "realtimeArrival":64020,
                            "arrivalDelay":0,
                            "scheduledDeparture":64020,
                            "realtimeDeparture":64020,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Tapiola (M) via Niittykumpu (M)",
                            "trip":{
                               "routeShortName":"125"
                            }
                         },
                         {
                            "scheduledArrival":65160,
                            "realtimeArrival":65160,
                            "arrivalDelay":0,
                            "scheduledDeparture":65160,
                            "realtimeDeparture":65160,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Matinkylä (M)",
                            "trip":{
                               "routeShortName":"158"
                            }
                         }
                      ]
                   },
                   "distance":679
                }
             },
             {
                "node":{
                   "place":{
                      "lat":60.16333,
                      "lon":24.66029,
                      "name":"Vehas",
                      "gtfsId":"HSL:2434201",
                      "code":"E4935",
                      "desc":"Nöykkiönkatu",
                      "locationType":"STOP",
                      "vehicleType":3,
                      "stoptimesWithoutPatterns":[
                         {
                            "scheduledArrival":62280,
                            "realtimeArrival":62398,
                            "arrivalDelay":118,
                            "scheduledDeparture":62280,
                            "realtimeDeparture":62400,
                            "departureDelay":120,
                            "realtime":true,
                            "realtimeState":"UPDATED",
                            "headsign":"Kiviruukki",
                            "trip":{
                               "routeShortName":"158"
                            }
                         },
                         {
                            "scheduledArrival":62400,
                            "realtimeArrival":62400,
                            "arrivalDelay":0,
                            "scheduledDeparture":62400,
                            "realtimeDeparture":62400,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Latokaski",
                            "trip":{
                               "routeShortName":"159"
                            }
                         },
                         {
                            "scheduledArrival":63240,
                            "realtimeArrival":63240,
                            "arrivalDelay":0,
                            "scheduledDeparture":63240,
                            "realtimeDeparture":63240,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Tillinmäki",
                            "trip":{
                               "routeShortName":"157"
                            }
                         },
                         {
                            "scheduledArrival":64080,
                            "realtimeArrival":64080,
                            "arrivalDelay":0,
                            "scheduledDeparture":64080,
                            "realtimeDeparture":64080,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Kiviruukki",
                            "trip":{
                               "routeShortName":"158"
                            }
                         },
                         {
                            "scheduledArrival":64200,
                            "realtimeArrival":64200,
                            "arrivalDelay":0,
                            "scheduledDeparture":64200,
                            "realtimeDeparture":64200,
                            "departureDelay":0,
                            "realtime":false,
                            "realtimeState":"SCHEDULED",
                            "headsign":"Latokaski",
                            "trip":{
                               "routeShortName":"159"
                            }
                         }
                      ]
                   },
                   "distance":717
                }
             }
          ]
       }
    }
 }